//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_Development_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public string ISBN { get; set; }
        public string Book_name { get; set; }
        public string Book_type { get; set; }
        public string Book_picture { get; set; }
        public string Book_author { get; set; }
        public string Book_location { get; set; }
    }
}
