//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_Development_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class lend
    {
        public string ISBN { get; set; }
        public System.DateTime Date_borrowed { get; set; }
        public string Id { get; set; }
    }
}
